services:
  # PostgreSQL ----------------------------------------------------------------
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      # Persists data between restarts
      - pgdata:/var/lib/postgresql/data

  # Redis ---------------------------------------------------------------------
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    # For a quick demo no config is needed; add a volume if you want persistence
    # volumes:
    #   - redisdata:/data

  # MinIO ---------------------------------------------------------------------
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: unless-stopped
    # Expose both the S3 API port (9000) and the Console UI port (9001)
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: rootuser
      MINIO_ROOT_PASSWORD: rootpassword
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

# --------------------------------------------------------------------------- #
# Named volumes — Docker stores these under /var/lib/docker/volumes on host   #
# --------------------------------------------------------------------------- #
volumes:
  pgdata:
  minio-data:
