import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { RegisterServiceWorker } from "@/components/register-service-worker";
import { ThemeProvider } from "@/components/theme-provider";
import { HeaderAuth } from "@/components/HeaderAuth";
import { ThemeToggle } from "@/components/ThemeToggle";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" disableTransitionOnChange>
          <div className="min-h-screen">
            <header className="w-full h-16 shadow">
              <div className="h-full container mx-auto flex items-center justify-between">
                <h1 className="text-2xl font-bold">EEE File Storage</h1>
                <div className="flex gap-4 items-center">
                  <ThemeToggle />
                  <HeaderAuth />
                </div>
              </div>
            </header>
            <main className="h-full flex flex-col items-center pt-32">
              {children}
            </main>
          </div>
        </ThemeProvider>
        <RegisterServiceWorker />
        <Toaster richColors closeButton />
      </body>
    </html>
  );
}
